# Uage:
# make	 	# compile all
# make clean	# remote ALL binaries and objects

# This is an example comment.

# Defind compile to be used.  
CC=gcc

# Name of final binary.
TARGET=supragma
 
all:    main.o
	$(CC) main.c -o $(TARGET)
 
clean:
	rm *.o $(TARGET)
